name: job_portal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.1.0+2

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.2
  file_picker: ^5.0.1
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  get: ^4.6.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.3"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_logo.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Black.ttf
  #       - asset: assets/fonts/Raleway-Bold.ttf
  #       - asset: assets/fonts/Raleway-ExtraBold.ttf
  #       - asset: assets/fonts/Raleway-ExtraLight.ttf
  #       - asset: assets/fonts/Raleway-Light.ttf
  #       - asset: assets/fonts/Raleway-Medium.ttf
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-SemiBold.ttf
  #       - asset: assets/fonts/Raleway-Thin.ttf
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
